### ISSUE TITLE
Allow wrapApiHandlerV2 to accept multiple types of AWS proxy events.

### ISSUE THREAD

**Issue by jvwiz** [onicagroup/sailplane#131]
Currently wrapApiHandlerV2 allows for APIGatewayProxyEventV2 type in handler. Could this be changed to allow more AWSGatewayProxy event types - **APIGatewayProxyEventV2**  | **APIGatewayProxyEventV2WithJWTAuthorizer** ?

**Comment by kernwig** [comment]
Hello @jvwiz .

APIGatewayProxyEventV2WithJWTAuthorizer is a subtype of APIGatewayProxyEventV2. Specifying both types in the function signature would still require you to type assert to the child type in order to tell Typescript which one you are using. So... well, type assert it.

To help you out, here's a middleware that I use in applications. It is app-specific, and so not part of Sailplane:

```ts
/**
 * Middleware for LambdaUtils to automatically manage AuthService context.
 */
export const authMiddleware = (): Required<middy.MiddlewareObj> => {
  const authSvc = Injector.get<AuthService>(AuthService);

  return {
    before: async (request) => {
      await authSvc.initForLambda(request.event as APIGatewayProxyEventV2WithJWTAuthorizer);
    },
    after: async () => {
      authSvc.destroy();
    },
    onError: async () => {
      authSvc.destroy();
    },
  };
};
```

And a very simple getUser API handler:

```ts
export const handler = LambdaUtils.wrapApiHandlerV2(async () => {
  return authSvc.getUser();
}).use(authMiddleware());
```

**Comment by jvwiz** [comment]
@kernwig .. Makes sense. Thanks for quick response.
