### ISSUE TITLE
Dependency on old version of middy surfaces resolved middy issues

### ISSUE THREAD

**Issue by russell-dot-js** [onicagroup/sailplane#16]
Ran into this while adding a custom middleware with "after" hook.

https://github.com/middyjs/middy/issues/264 has been resolved in Middy since March (https://github.com/middyjs/middy/pull/312)

However, since lambda-utils has dependency on old version of middy, and uses the cors middleware, custom "after" middlewares cannot be implemented as they are called with `null, null`

I will put up a PR for ya

**Comment by kernwig** [comment]
Thank you. We originally avoided updating Middy because they introduced a hard dependency on FunctionShield. That apparently has been resolved as of Middy v0.22.0. 👍 

I don't remember running into this problem with error handler and CORS though. Are you using the LambdaUtils.unhandledExceptionMiddleware instead of the one provided by Middy?

**Comment by russell-dot-js** [comment]
Opened: https://github.com/onicagroup/sailplane/pull/17/files
and https://github.com/onicagroup/sailplane/pull/18

**Comment by russell-dot-js** [comment]
@kernwig yes, we are using LambdaUtils.wrapApiHandler

Simple test case is to try implementing a custom after hook before and after pr.

e.g.

```
LambdaUtils.wrapApiHandler(handler).use({
  after: (...args) => console.log(args);
});
```

**Comment by kernwig** [comment]
Released. https://github.com/onicagroup/sailplane/releases/tag/lambda-utils-2.0.0
