### ISSUE TITLE
[logger] Feature to disable sailplane logs

### ISSUE THREAD

**Issue by sharabiania** [onicagroup/sailplane#67]
https://github.com/onicagroup/sailplane/blob/08557b311ea83c62c61980761397080a012cf7aa/injector/lib/injector.ts#L79

These debug logs are all over the place in CloudWatch and when running Unit tests.

At the same time we don't want to disable the `logger` logs for the whole project using the Environment Variables.

Is there a way (or can we add this feature) to be able to disable the injector logs, Or limit them to only Errors or Warnings?

**Comment by kernwig** [comment]
I suggest using log levels strategically. DEBUG should be noisy. General operations should be limited to INFO and above. You can then set your log level at INFO and only lower it when debugging something.

You appear to want to control log level by logger name. That seems doable. Leaving this issue here as an enhancement request.

**Comment by kernwig** [comment]
logger v2.0.3 added log level NONE. Does this help?

package.json:
```
  "scripts": {
    "test": "LOG_LEVEL=NONE jest",
```
