### ISSUE TITLE
LambdaUtils: Missing properly casted Type for APIGatewayProxyEvent objects ran through middleware

### ISSUE THREAD

**Issue by voodooGQ** [onicagroup/sailplane#9]
Currently when running the Serverless/Typescript/Sailplane stack the middleware converts the `AWS.APIGatewayProxyEvent`s attributes before being passed into the handler. Since `tsconfig` see's it as a standard `APIGatewayProxyEvent` it assumes the `body` element should be a JSON string, but that's cast to an object during the middleware conversion.

A new interface should be supplied with the `lambda-utils` module that makes the casted interface accessible.

**Comment by kernwig** [comment]
So this is just an attempt to avoid casting body? I haven't worried about this, because I still want to cast the body to the actual type of the JSON content. For instance, I have a lambda that finds people based on search criteria, so the first line of the Lambda is:

`    const criteria = (event.body as any) as PersonCriteria;`

Where of course I have defined the `interface PersonCriteria` in my package that is shared between the lambda and the client. Is there much benefit to defining a type to cast to `any`, when type safety demands that we cast again to the actual type? (I'm open to it: convince me.)

**Comment by voodooGQ** [comment]
> Still getting up to speed on Typescript, so if there's a better way to handle this I'm all ears.

^ That's a quotation from the PR that probably would have been served well over here as well. 

I'm not really trying to convince anyone of anything honestly. The tsconfig as part of my editor was giving me constant errors because it was expecting a standard APIGatewayProxyEvent object. Until I cast `body` to `any` it wouldn't allow me to work with the sailplane library without creating the cast. 

I think in this case because I'm having to make that change consistently while working with my Serverless Application that the interface is better served being part of the library. In addition if other changes need to happen to it in the future (adding info for instance as this lib grows) the libraries feeding off it will automatically be setup for success.

I'm 100% open to casting directly if you think that's better. This is the first job I've worked with Typescript (plus about 15 other libs) so I'm by no means a standards expert and would love your insight on it.

**Comment by voodooGQ** [comment]
Whoops! Sorry, hit the unassign button by accident, can't get it back now. @kernwig

**Comment by kernwig** [comment]
My opposition stems from the idea that this would mostly serve to encourage weak type checking. You should be casting to the actual type of the body. Casting to `any` (and declaring that type on the parameter) allows you to skip the casting, but be vulnerable to typos.

It's a bit ironic though, because only by _using_ this type in the function declaration are you opening yourself to not properly casting the body to the proper type. Providing the type as you have here doesn't require its use either... so I'm really conflicted on the idea. It does have a bit of value in accuracy of the type that truly comes back and it does simplify my example cast above from 
`const criteria = (event.body as any) as PersonCriteria;`
to just
`const criteria = event.body as PersonCriteria;`
so that's nice.

What do you think @sdechgan @jmhummel?

**Comment by kernwig** [comment]
Just to document: I came around on this with the PR now including changing the types of pathParameters and queryStringParameters to no longer be nullable. This provides an interface that fully reflects the event structure as returned from LambdaUtils.
